# Generated by Django 3.2.16 on 2024-07-15 20:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('main_filter', django.db.models.manager.Manager()),
            ],
        ),
    ]
