# Generated by Django 3.2.16 on 2024-07-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='load_images', verbose_name='Фото'),
        ),
    ]
