# Generated by Django 3.2.16 on 2024-07-14 22:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comments_post'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('database_query_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
